server:
  port: 8642

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persondb
    username: user1
    password: pass1
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /swagger-ui.html
