version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresql
    #restart: always
    environment:
      POSTGRES_DB: persondb
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass1
    ports:
      - 5432:5432